# Generated by Django 5.1.7 on 2025-04-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('security_question', models.TextField()),
                ('security_answer', models.TextField()),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('company', 'Company')], max_length=10)),
            ],
        ),
    ]
