# Generated by Django 5.1.7 on 2025-04-04 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='U0000', editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('company', 'Company')], default='employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question',
            field=models.CharField(choices=[("What was your first pet's name?", "What was your first pet's name?"), ('What city were you born in?', 'What city were you born in?'), ("What is your mother's maiden name?", "What is your mother's maiden name?"), ('What was the name of your first school?', 'What was the name of your first school?')], max_length=255),
        ),
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
