# Generated by Django 5.1.7 on 2025-04-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_user_created_at_user_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Accounting', 'Accounting'), ('Marketing', 'Marketing'), ('Part Timer', 'Part Timer'), ('Event Crew', 'Event Crew'), ('Software Engineer', 'Software Engineer'), ('Data Analyst', 'Data Analyst'), ('Product Manager', 'Product Manager'), ('UX Designer', 'UX Designer'), ('DevOps Engineer', 'DevOps Engineer'), ('QA Engineer', 'QA Engineer'), ('System Administrator', 'System Administrator'), ('Technical Writer', 'Technical Writer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Mobile Developer', 'Mobile Developer'), ('Data Scientist', 'Data Scientist'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Cloud Architect', 'Cloud Architect'), ('Network Engineer', 'Network Engineer'), ('Security Specialist', 'Security Specialist')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='api.user', to_field='uid')),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'db_table': 'job_position',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'position'), name='unique_user_position')],
            },
        ),
    ]
